export const plans = [
    {
      name: "Starter",
      price: "$99",
      period: "month",
      features: {
        conversations: "500 interactions/month",
        skus: "250 SKUs",
        recommendations: "Upselling (complementary product suggestions)",
        insights: "Weekly customer interaction summary",
        support: "Email support",
        stores: "QR setup for 1 store",
        branding: true,
        integrations: true,
        aiCustomization: false,
        employeeAccess: true,
      },
    },
    {
      name: "Basic",
      price: "$199",
      period: "month",
      features: {
        conversations: "2,500 interactions/month",
        skus: "1,000 SKUs",
        recommendations: "AI-driven upselling & cross-selling with bundling",
        insights: "Weekly sales & behavior trends report",
        support: "Priority email support",
        stores: "QR setup for up to 3 stores",
        branding: true,
        integrations: true,
        aiCustomization: true,
        employeeAccess: true,
      },
    },
    {
      name: "Pro",
      price: "$399",
      period: "month",
      popular: true,
      features: {
        conversations: "10,000 interactions/month",
        skus: "5,000 SKUs",
        recommendations:
          "Fully personalized, real-time offers & predictive analytics",
        insights: "Weekly in-depth analytics & predictive insights",
        support: "Email, chat & phone support",
        stores: "QR setup for up to 6 stores",
        branding: true,
        integrations: true,
        aiCustomization: true,
        employeeAccess: true,
      },
    },
    {
      name: "Enterprise",
      price: "Custom",
      subtitle: "Starting at $999/month",
      features: {
        conversations: "Unlimited",
        skus: "Unlimited",
        recommendations:
          "Fully personalized, real-time offers & predictive analytics",
        insights: "Real-time dashboards & predictive insights",
        support: "24/7 dedicated account manager & premium support",
        stores: "QR setup for unlimited stores",
        branding: "Full branding & UI customization",
        integrations: true,
        aiCustomization: true,
        employeeAccess: true,
      },
    },
  ];
